# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20170329_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='radius',
        ),
        migrations.AlterField(
            model_name='spots',
            name='lat',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='spots',
            name='log',
            field=models.IntegerField(default=''),
        ),
    ]
